"""Adding telephone column 2

Revision ID: 2dcc5211493f
Revises: d952e8585942
Create Date: 2023-04-17 23:10:41.800614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcc5211493f'
down_revision = 'd952e8585942'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'addresses_temp',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True, nullable=False),
        sa.Column('npi', sa.Integer, sa.ForeignKey('npi.npi'), nullable=False),
        sa.Column('address', sa.String, nullable=False),
    )

    # Copy the data from the old table to the new temporary table
    op.execute("INSERT INTO addresses_temp (id, npi, address) SELECT id, npi, address FROM addresses")

    # Drop the old table
    op.drop_table('addresses')

    # Rename the temporary table to the original table name
    op.rename_table('addresses_temp', 'addresses')

    op.add_column('npi', sa.Column('telephone', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taxonomies', 'npi',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('taxonomies', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('npi', 'npi',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('npi', 'telephone')
    op.alter_column('addresses', 'npi',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('npi', 'telephone')

    # ### end Alembic commands ###
