"""Initial schema

Revision ID: d952e8585942
Revises: 
Create Date: 2023-04-17 20:53:21.049059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd952e8585942'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Create a new temporary table with the desired schema
    op.create_table(
        'addresses_temp',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True, nullable=False),
        sa.Column('npi', sa.Integer, sa.ForeignKey('npi.npi'), nullable=False),
        sa.Column('address', sa.String, nullable=False),
    )

    # Copy the data from the old table to the new temporary table
    op.execute("INSERT INTO addresses_temp (id, npi, address) SELECT id, npi, address FROM addresses")

    # Drop the old table
    op.drop_table('addresses')

    # Rename the temporary table to the original table name
    op.rename_table('addresses_temp', 'addresses')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taxonomies', 'npi',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('taxonomies', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('npi', 'npi',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('addresses', 'npi',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('addresses', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
