
name: Test and Lint

on:
  pull_request:
    branches: ["**"] #run on any branch only when a pull request is created

jobs:

  test:
    strategy:
      matrix:
        python-versions: ["3.9"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Setup Python
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Bootstrap
        run: |
          pip install -r requirements.txt
          pip install -e .
          python tests/test_npi_lookup.py
